name: Called Workflow - build
on: 
    workflow_call:
      outputs:
        success:
          description: set to true if the workflow has completed
          value: ${{ jobs.build-cicd-tools.outputs.success_value }}
      inputs:
        tag:
          description: 'The version tag to use for stamping build artifacts and naming generated archives'
          required: true
          type: string
        prerelease:
          description: 'Set to true if published build is a prerelease'
          type: boolean
          required: true
      
               
jobs:
  build-cicd-tools:
    runs-on: ubuntu-latest
    outputs:
      success_value: ${{ steps.complete.outputs.success }}
    steps:
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with:
          distribution: 'corretto'
          java-version: '17'
         
      - name: Fetch Code @ tag ${{ inputs.tag }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: refs/tags/${{ inputs.tag }}

      - name: Execute build
        run: ./gradlew -Ppackage_version=${{ inputs.tag }} build
      
      - name: Execute jsonpath-query Smoke Tests
        run: smoke-tests/jsonpath-query-smoke-test.sh
      
      - name: Execute archive-downloader Smoke Tests
        run: smoke-tests/archive-downloader-smoke-test.sh

      - name: Execute cxflow-downloader Smoke Tests
        run: smoke-tests/cxflow-downloader-smoke-test.sh
       
      - name: Copy artifacts
        run: |
            mkdir artifacts
            cp cxflow-downloader/build/libs/cxflow-downloader.jar artifacts/
            cp cxflow-downloader/build/libs/cxflow-downloader.jar artifacts/cxflow-downloader-${{ inputs.tag }}.jar
            cp archive-downloader/build/libs/archive-downloader.jar artifacts/
            cp archive-downloader/build/libs/archive-downloader.jar artifacts/archive-downloader-${{ inputs.tag }}.jar

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: artifacts/*.jar
          artifactContentType: application/zip
          name: ${{ inputs.tag }}
          prerelease: ${{ inputs.prerelease }}
          replacesArtifacts: true
          tag: ${{ inputs.tag }}

      - name: Set Output
        id: complete
        run: echo "success=true" >> "$GITHUB_OUTPUT"
