name: CI Build
on: 
    push:

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
              with:
                distribution: 'corretto'
                java-version: '17'
       
            - name: Fetch Code
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    
            - name: Build
              run: ./gradlew build
            
            - name: Execute jsonpath-query Smoke Tests
              run: smoke-tests/jsonpath-query-smoke-test.sh
            
            - name: Execute archive-downloader Smoke Tests
              run: smoke-tests/archive-downloader-smoke-test.sh

            - name: Execute cxflow-downloader Smoke Tests
              run: smoke-tests/cxflow-downloader-smoke-test.sh
    