name: CI Build
on: 
    push:

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch Code
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    
            - name: Build
              run: ./gradlew build
            
            - name: Execute jsonpath-query Smoke Tests
              run: smoke-tests/jsonpath-query-smoke-test.sh
            
            - name: Execute archive-downloader Smoke Tests
              run: smoke-tests/archive-downloader-smoke-test.sh

            - name: Execute cxflow-downloader Smoke Tests
              run: smoke-tests/cxflow-downloader-smoke-test.sh
    