name: Called Workflow - invoke-build
on: 
    workflow_call:
      inputs:
        tag:
          description: 'The version tag string'
          required: true
          type: string
        prerelease:
          description: 'Set to true if publishing a pre-release.'
          required: true
          type: boolean
              
jobs:
  create-tag:
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Tag repo ${{ inputs.tag }}
        uses: richardsimko/update-tag@e173a8ef8f54ab526a91dad6139a25efed62424c
        with:
          tag_name: ${{ inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  publish-release:
    needs: [create-tag]
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ inputs.tag }}
      prerelease: ${{ inputs.prerelease }}

  remove-tag-on-failure:
    needs: [create-tag, publish-release]
    runs-on: cx-public-ubuntu-x64
    if: always()
    env:
      BUILD_SUCCESS: ${{ needs.publish-release.outputs.success }}
    steps:
      - name: Fetch Code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        if: env.BUILD_SUCCESS != 'true'

      - name: Remove CodeTag
        run: git push origin ':refs/tags/${{ inputs.tag }}'
        if: env.BUILD_SUCCESS != 'true'

